import esbuild from "esbuild";
import process from "process";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/
`;

const prod = process.argv[2] === "production";
const store = process.argv[2] === "store";

const builtins = [
  "assert", "buffer", "child_process", "cluster", "crypto", "dgram", "dns",
  "domain", "events", "fs", "http", "https", "module", "net", "os", "path",
  "process", "punycode", "querystring", "readline", "repl", "stream",
  "string_decoder", "timers", "tls", "tty", "url", "util", "v8", "vm",
  "worker_threads", "zlib",
];

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian", "electron",
    "@codemirror/autocomplete", "@codemirror/collab",
    "@codemirror/commands", "@codemirror/language",
    "@codemirror/lint", "@codemirror/search",
    "@codemirror/state", "@codemirror/view",
    "@lezer/common", "@lezer/highlight", "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2020",
  logLevel: "info",
  sourcemap: false,
  treeShaking: true,
  outfile: "main.js",
  minify: prod || store,
});

if (prod) {
  await context.rebuild();
  // Obfuscation — solo para distribución externa (Gumroad/ZIP)
  try {
    const { execSync } = await import("child_process");
    execSync(
      `npx javascript-obfuscator main.js --output main.js ` +
      `--compact true --control-flow-flattening true --control-flow-flattening-threshold 0.75 ` +
      `--dead-code-injection true --dead-code-injection-threshold 0.5 ` +
      `--string-array true --string-array-encoding rc4 ` +
      `--string-array-threshold 0.75 --transform-object-keys true ` +
      `--unicode-escape-sequence true ` +
      `--disable-console-output true`,
      { stdio: "inherit" }
    );
    console.log(" Obfuscation complete");
  } catch { console.warn(" javascript-obfuscator not installed."); }
  process.exit(0);
}

if (store) {
  await context.rebuild();
  console.log(" ⚠️  Store build complete — main.js clean for Obsidian community review.");
  console.log("    NEVER submit an obfuscated build (npm run build) to obsidian-releases.");
  console.log("    Only this build passes review.");
  process.exit(0);
}

await context.watch();
