import { Platform, requestUrl } from "obsidian";
import { CopilotSettings } from "../settings";
import { t } from "../i18n";
import { WORKER_URL } from "./workerConfig";

// Universal HTTP client: native fetch() in Electron, requestUrl fallback on mobile.
async function fetchWithFallbackFn(url: string, options: RequestInit): Promise<Response> {
  if (typeof window !== "undefined" && typeof window.fetch !== "undefined") {
    // eslint-disable-next-line @typescript-eslint/no-unsafe-call
    // eslint-disable-next-line @typescript-eslint/no-unsafe-call, @typescript-eslint/no-unsafe-member-access
    return window.fetch(url, options);
  }
  const r = await requestUrl({ url, method: options.method, headers: options.headers as Record<string, string>, body: options.body as string });
  return new Response(r.text, { status: r.status, headers: new Headers(r.headers) });
}

export type LicenseTier = "free" | "pro";

export interface ActivateResult {
  tier: LicenseTier;
  error?: string;       // user-facing message when key is rejected
  cloudResponse?: LicenseValidationResponse;  // raw response for debugging
}

export interface LicenseInfo {
  tier: LicenseTier;
  key: string;
  validUntil: number;
  features: string[];
}

interface LicenseValidationResponse {
  valid?: boolean;
  tier?: string;
  error?: string;
  reason?: string;
  expiresAt?: number;
  features?: string[];
}

/**
 * LicenseManager — validates license keys and controls feature access.
 * Free tier: unlimited chat (bring your own API key), 3 tools, no agent mode. Copilot AI: 5 queries/day free trial.
 * Pro tier: unlimited messages, agent mode, all tools, web search, PDF images
 *
 * Cloud-first validation via Cloudflare Worker.
 * Keys are generated by Lemon Squeezy (UUID format) — no local checksum.
 * Grace period: 24h offline window if the cloud is unreachable.
 */
export class LicenseManager {
  private currentLicense: LicenseInfo | null = null;
  private messageCount = 0;
  private messageDay = new Date().toDateString();
  private persistFn: (() => { count: number; day: string }) | null = null;
  private restoreFn: ((data: { count: number; day: string } | null) => void) | null = null;
  private boundFingerprint: string | null = null;

  setPersistence(
    save: () => { count: number; day: string },
    restore: (data: { count: number; day: string } | null) => void
  ): void {
    this.persistFn = save;
    this.restoreFn = restore;
  }

  restoreMessageCount(data: { count: number; day: string } | null): void {
    if (data && data.day === new Date().toDateString()) {
      this.messageCount = data.count;
      this.messageDay = data.day;
    }
  }

  /** Store fingerprint for license binding (persisted in data.json) */
  storeFingerprint(fp: string | null): void {
    this.boundFingerprint = fp;
  }

  getStoredFingerprint(): string | null {
    return this.boundFingerprint;
  }

  /** Public getter for persistence */
  getPersistableState(): { count: number; day: string } {
    return { count: this.messageCount, day: this.messageDay };
  }

  /** Demo key only works in debug/development mode */
  private static isDebugMode(): boolean {
    try {
      return typeof process !== "undefined" && ((process as unknown as { env: Record<string, string | undefined> })?.env?.NODE_ENV === "development" || (process as unknown as { env: Record<string, string | undefined> })?.env?.COPILOT_DEBUG === "1");
    } catch { return false; }
  }

  /**
   * Validate a license key against the Cloudflare Worker.
   * Keys are generated by Lemon Squeezy (UUID format, e.g. "056B9494-...").
   * No local format validation — the cloud is the source of truth.
   */
  async activate(key: string, serverUrl?: string): Promise<ActivateResult> {
    // Demo key — only works in debug mode
    if (key === "COPIPRO-DEMO-DEMO-DEMO") {
      if (!LicenseManager.isDebugMode()) return { tier: "free", error: t("license.demoKeyDenied") };
      this.currentLicense = { tier: "pro", key, validUntil: Date.now() + 365 * 24 * 3600 * 1000, features: this.getProFeatures() };
      return { tier: "pro" };
    }

    // FREE tier — no key needed
    if (!key || key === "FREE") {
      this.currentLicense = { tier: "free", key: "FREE", validUntil: 0, features: this.getFreeFeatures() };
      return { tier: "free" };
    }

    // Use stored fingerprint (from data.json) if available, so re-activation
    // reuses the same device binding instead of registering a new device each time.
    // Falls back to generating a fresh fingerprint only on first activation.
    const currentFp = this.boundFingerprint ?? LicenseManager.getFingerprint();

    // Cloud validation via Cloudflare Worker
    const validationUrl = serverUrl || WORKER_URL + "/v1/validate";
    try {
      const response = await fetchWithFallbackFn(validationUrl, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ key, fingerprint: currentFp, pluginVersion: "1.6.0" }),
      });

      if (!response.ok) {
        const errText = await response.text();
        console.warn(`[LicenseManager] Worker returned ${response.status}: ${errText.substring(0, 200)}`);
        const err = this.graceFallbackResult();
        return { ...err, error: t("license.serverError", { status: response.status }) };
      }

      const data = await response.json() as LicenseValidationResponse;

      if (!data.valid) {
        this.currentLicense = { tier: "free", key: "FREE", validUntil: 0, features: this.getFreeFeatures() };
        const reason = data.error || data.reason || "unknown";
        return {
          tier: "free",
          error: t("license.rejected", { reason }),
          cloudResponse: data,
        };
      }

      this.currentLicense = {
        tier: (data.tier as LicenseTier) || "pro",
        key,
        validUntil: (data.expiresAt || 0) * 1000,
        features: data.features || this.getProFeatures(),
      };
      this.boundFingerprint = currentFp;
      return { tier: (data.tier as LicenseTier) || "pro", cloudResponse: data };
    } catch (err) {
      // Network error — log the cause for debugging
      const errMsg = err instanceof Error ? err.message : String(err);
      console.warn(`[LicenseManager] Activation failed: ${errMsg}`);

      // No internet → grace period
      const result = this.graceFallbackResult();
      if (result.tier === "pro") return result;
      return { tier: "free", error: t("license.offlineError") };
    }
  }

  /** Grace period: if we had a valid Pro license, allow 24h offline window */
  private graceFallbackResult(): ActivateResult {
    if (this.currentLicense?.tier === "pro") {
      const graceWindow = Date.now() - 24 * 3600 * 1000;
      if (this.currentLicense.validUntil > graceWindow) return { tier: "pro" };
    }
    this.currentLicense = { tier: "free", key: "FREE", validUntil: 0, features: this.getFreeFeatures() };
    return { tier: "free" };
  }

  /** Generate a device fingerprint for identification (not for encryption) */
  static getFingerprint(): string {
    try {
      const parts = [
        typeof navigator !== "undefined" ? String(navigator.hardwareConcurrency ?? 0) : "0",
        Platform.isDesktop ? "desktop" : Platform.isMobile ? "mobile" : "unknown",
        // Device fingerprint uses safe APIs only — no navigator.userAgent (avoids OS detection)
        typeof window !== "undefined" ? "electron" : "node",
        typeof screen !== "undefined" ? `${screen.width}x${screen.height}` : "",
        new Intl.DateTimeFormat().resolvedOptions().timeZone || "",
      ];
      return LicenseManager.djb2(parts.join("|")).toString(36);
    } catch { return "unknown"; }
  }

  private static djb2(str: string): number {
    let hash = 5381;
    for (let i = 0; i < str.length; i++) hash = ((hash << 5) + hash) + str.charCodeAt(i);
    return Math.abs(hash);
  }

  isValid(): boolean {
    if (!this.currentLicense) return true;
    if (this.currentLicense.tier === "free") return true;
    return Date.now() < this.currentLicense.validUntil;
  }

  getTier(): LicenseTier {
    if (!this.isValid()) return "free";
    return this.currentLicense?.tier ?? "free";
  }

  hasFeature(feature: string): boolean {
    if (!this.currentLicense) return this.getFreeFeatures().includes(feature);
    if (!this.isValid()) return false;
    return this.currentLicense.features.includes(feature);
  }

  trackMessage(): boolean {
    const today = new Date().toDateString();
    if (this.messageDay !== today) { this.messageCount = 0; this.messageDay = today; }
    this.messageCount++;
    try {
      if (this.persistFn) this.persistFn();
    } catch (err) {
      console.warn("[LicenseManager] Failed to persist message count:", err);
    }
    return this.isAllowed();
  }

  isAllowed(): boolean {
    if (this.getTier() === "pro") return true;
    return this.messageCount <= 5; // Copilot AI free trial: 5/day (enforced server-side)
  }

  getRateLimit(): { used: number; limit: number; tier: LicenseTier } {
    return { used: this.messageCount, limit: this.getTier() === "pro" ? Infinity : 5, tier: this.getTier() };
  }

  getActiveFeatures(): string[] {
    return this.currentLicense?.features ?? this.getFreeFeatures();
  }

  /** Free users get 5 Copilot AI queries/day via server-side tracking */
  canUseBudget(): boolean { return true; }

  private getFreeFeatures(): string[] { return ["chat_basic", "read_note", "read_pdf", "find_files"]; }

  private getProFeatures(): string[] {
    return ["chat_unlimited", "agent_mode", "all_tools", "web_search", "pdf_images", "rag_semantic", "export_chat", "slash_commands", "multi_provider", "priority_support"];
  }

  /** Features unlocked for everyone. Slash commands use user's provider (zero cost). */
  hasUnlockedFeature(feature: string): boolean {
    const unlocked = ["export_chat", "slash_commands", "multi_provider"];
    return unlocked.includes(feature);
  }

  canUseAgent(): boolean { return this.hasFeature("agent_mode") || this.hasFeature("all_tools"); }
  canUseWebSearch(): boolean { return this.hasFeature("web_search") || this.hasFeature("all_tools"); }
  canUsePdfImages(): boolean { return this.hasFeature("pdf_images") || this.hasFeature("all_tools"); }

  applyRestrictions(settings: CopilotSettings): CopilotSettings {
    if (this.getTier() === "pro") return settings;
    return {
      ...settings,
      enableAgentMode: false,
      webSearchEnabled: false,
      enableSemanticSearch: false,
      visionEnabled: false,
      fallbackEmbeddingProvider: "",
      fallbackVisionProvider: "",
    };
  }
}
