import { LicenseManager } from "../services/LicenseManager";

describe("LicenseManager", () => {
  let lm: LicenseManager;

  beforeEach(() => {
    lm = new LicenseManager();
  });

  describe("Key format validation", () => {
    // Keys are now generated by Lemon Squeezy (UUID format).
    // No local format validation — the cloud Worker is the source of truth.
    // Any non-empty string is forwarded to the Worker for validation.
    // Empty and "FREE" are treated as free tier.
  });

  describe("Tier management", () => {
    test("defaults to free tier", () => {
      expect(lm.getTier()).toBe("free");
    });

    test("activates free tier with empty key", () => {
      lm.activate("");
      expect(lm.getTier()).toBe("free");
    });

    test("activates free tier with FREE key", () => {
      lm.activate("FREE");
      expect(lm.getTier()).toBe("free");
    });
  });

  describe("Feature gating", () => {
    test("free tier cannot use agent", () => {
      lm.activate("FREE");
      expect(lm.canUseAgent()).toBe(false);
    });

    test("free tier cannot use web search", () => {
      lm.activate("FREE");
      expect(lm.canUseWebSearch()).toBe(false);
    });

    test("free tier cannot use PDF images", () => {
      lm.activate("FREE");
      expect(lm.canUsePdfImages()).toBe(false);
    });
  });

  describe("Rate limiting", () => {
    test("free tier allows up to 50 messages", () => {
      lm.activate("FREE");
      for (let i = 0; i < 50; i++) {
        expect(lm.trackMessage()).toBe(true);
      }
      expect(lm.trackMessage()).toBe(false); // 51st message blocked
    });

    test("rate limit resets on new day", () => {
      lm.activate("FREE");
      for (let i = 0; i < 51; i++) lm.trackMessage();
      expect(lm.trackMessage()).toBe(false);

      // Simulate new day by manipulating the private field
      (lm as any).messageDay = "yesterday";
      expect(lm.trackMessage()).toBe(true); // counter reset
    });

    test("pro tier has no limit", () => {
      // We can't test pro without a valid key, but we can check isAllowed logic
      expect(lm.isAllowed()).toBe(true); // free tier, 0 messages
    });

    test("getRateLimit returns correct values", () => {
      lm.activate("FREE");
      lm.trackMessage();
      const limit = lm.getRateLimit();
      expect(limit.used).toBe(1);
      expect(limit.limit).toBe(50);
      expect(limit.tier).toBe("free");
    });
  });

  describe("Fingerprint", () => {
    test("getFingerprint returns a string", () => {
      const fp = LicenseManager.getFingerprint();
      expect(typeof fp).toBe("string");
      expect(fp.length).toBeGreaterThan(0);
    });

    test("getFingerprint is consistent", () => {
      const fp1 = LicenseManager.getFingerprint();
      const fp2 = LicenseManager.getFingerprint();
      expect(fp1).toBe(fp2);
    });
  });

  describe("Demo key", () => {
    test("demo key requires debug mode", async () => {
      // In test environment (no NODE_ENV=development), demo key should be rejected
      const result = await lm.activate("COPIPRO-DEMO-DEMO-DEMO");
      // Returns { tier: "free", error: "..." } since debug mode is off
      expect(result.tier).toBe("free");
      expect(result.error).toBeDefined();
      expect(lm.getTier()).toBe("free");
    });
  });

  describe("applyRestrictions", () => {
    test("pro tier preserves settings", () => {
      // Can't test pro activation in unit test, but verify free behavior
      const settings = { enableAgentMode: true, webSearchEnabled: true } as any;
      const restricted = lm.applyRestrictions(settings);
      expect(restricted.enableAgentMode).toBe(false);
      expect(restricted.webSearchEnabled).toBe(false);
    });
  });

  describe("Message count persistence", () => {
    test("getPersistableState returns current state", () => {
      lm.activate("FREE");
      lm.trackMessage();
      lm.trackMessage();
      const state = lm.getPersistableState();
      expect(state.count).toBe(2);
      expect(typeof state.day).toBe("string");
    });

    test("restoreMessageCount restores same-day state", () => {
      const today = new Date().toDateString();
      lm.restoreMessageCount({ count: 5, day: today });
      expect(lm.getPersistableState().count).toBe(5);
    });

    test("restoreMessageCount ignores different-day state", () => {
      lm.restoreMessageCount({ count: 5, day: "2024-01-01" });
      expect(lm.getPersistableState().count).toBe(0);
    });
  });
});
